src/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index']);

Route::get('/assign_company', [App\Http\Controllers\CompanyController::class, 'assignParams'])->name('assign_company');

Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login');
Route::get('/login/redirect', [\App\Http\Controllers\Auth\SocialController::class, 'loginRedirect']);

Route::prefix('param')->group(
    function () {
        Route::get('/percent-deviation', [\App\Http\Controllers\ParamController::class, 'percentOfDeviation'])->name('param.showPercentDeviation');
        Route::get('/change-deviation', [\App\Http\Controllers\ParamController::class, 'changePercentOfDeviation'])->name('param.changePercentOfDeviation');
        Route::post('/update-percent', [\App\Http\Controllers\ParamController::class, 'updatePercentOfDeviation'])->name('param.updatePercentOfDeviation');
    }
);

Route::prefix('plan')->group(
    function () {
        Route::get('/step-two', [\App\Http\Controllers\PlanController::class, 'step2'])->name('plan.step2');
        Route::get('/edit-plan', [\App\Http\Controllers\PlanController::class, 'editPlan'])->name('plan.editPlan');
    }
);

Route::prefix('report')->group(
    function () {
        Route::get('/show-report-month', [\App\Http\Controllers\ReportController::class, 'showReportCurMonth'])->name('report.showReport');
        Route::get('/show-report', [\App\Http\Controllers\ReportController::class, 'showReportForCorrect'])->name('report.showReportForCorrect');
    }
);

Route::resources(
    [
        'plan'    => \App\Http\Controllers\PlanController::class,
        'company' => \App\Http\Controllers\CompanyController::class,
        'param'   => \App\Http\Controllers\ParamController::class,
        'report'  => \App\Http\Controllers\ReportController::class,
        'template'  => \App\Http\Controllers\TemplateController::class,
    ]
);

src/app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Aggregator\PlanAggregator;
use App\Models\Data;
use App\Models\Param;
use App\Models\Template;
use App\Models\Variables;
use App\Months;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class PlanController extends Controller
{
    private const TYPE_DATA          = 'data';
    private const TYPE_FACT_PREVIOUS       = 'fact_previous';
    private const TYPE_PREDICT_CURRENT = 'predict_current';

    public function __construct()
    {
        $this->middleware('web');
    }

    public function show(Request $request, $id): Renderable
    {
        $currentYear = (int)$request->get('year', date('Y'));

        if (null !== $id) {
            $currentReport = Template::all()->where('company_id', $id)->first();
        }

        $lastYear = Data::all()->where('template_id', $currentReport->id)->where('year', $currentYear - 1)->first();
        $thisYear = Data::all()->where('template_id', $currentReport->id)->where('year', $currentYear)->first();
        $nextYear = Data::all()->where('template_id', $currentReport->id)->where('year', $currentYear + 1)->first();

        $params = Param::all()->whereIn('id', $currentReport->params)->sortBy('paragraph')->keyBy('id')->toArray();

        $aggregator = new PlanAggregator(
            $lastYear->data ?? null,
            $thisYear->data ?? null,
            $nextYear->data ?? null,
            $params,
            $thisYear->fact_previous ?? null,
            $thisYear->predict_current ?? null,
        );

        return view(
            'plan.show',
            [
                'currentYear'   => $currentYear,
                'currentReport' => $currentReport,
                'months'        => Months::get(),
                'years'         => range(date('Y') - 2, date('Y') + 2),
                'reports'       => Template::all(),
                'aggregated'    => $aggregator->aggregate(),
            ]
        );
    }

    public function index(Request $request)
    {
        $ordinal     = 0;
        $companies   = Template::all();
        $currentYear = (int)$request->get('year', date('Y'));

        $reports = [];

        foreach ($companies as $item) {
            ++ $ordinal;
            $data   = Data::all()->where('year', $currentYear)->where('template_id', $item->id)->first();
            $report = Template::all()->where('company_id', $item->company_id)->first();
            if ($data) {
                $report->isCurrentYearPlan = true;
            }
            $report->ordinal = $this->getOrdinal($ordinal);
            $reports[]       = $report;
        }

        return view(
            'plan.index',
            [
                'reports'     => $reports,
                'currentYear' => $currentYear,
                'years'       => range(date('Y') - 2, date('Y') + 2),
            ]
        );
    }

    protected function getOrdinal(int $ordinal)
    {
        switch ($ordinal) {
            case $ordinal < 10 && $ordinal > 0:
                return '000' . $ordinal;
                break;
            case $ordinal >= 10 && $ordinal < 100:
                return '00' . $ordinal;
                break;
            case $ordinal >= 100 && $ordinal < 1000:
                return '0' . $ordinal;
                break;
            default:
                return $ordinal;
        }
    }

    public function create(Request $request)
    {
        return view(
            'plan.create',
            [
                'reports' => Template::all(),
                'years'   => range(date('Y') - 2, date('Y') + 2),
            ]
        );
    }

    public function editPlan(Request $request)
    {
        $percent = Variables::where('key', 'percentOfDeviation')->first();
        $report  = Template::where('company_id', $request->get('id'))->first();

        if ($report->params === null) {
            return redirect('template/' . $report->id . '/edit')->with('error', 'Заполните параметры для шаблона ' . $report->company->company_name);
        }

        $data   = Data::where('template_id', $report->id)->where('year', $request->get('year'))->first();
        $params = Param::all()->whereIn('id', array_keys($report->params))->keyBy('id')->toArray();
        $months = Months::get();
        unset($months[12], $months[13], $months[14], $months[15]);

        $existingData    = [];
        $existingPredict = [];
        $existingFact    = [];

        if (null !== $data) {
            $existingData    = $data->data;
            $existingFact    = $data->fact_previous;
            $existingPredict = $data->predict_current;
        }

        return view(
            'plan.adjustment',
            [
                'months'          => $months,
                'report'          => Param::getSortedParams($this->findParamForId($report->params)),
                'year'            => $request->get('year'),
                'existingData'    => $existingData,
                'existingFact'    => $existingFact,
                'existingPredict' => $existingPredict,
                'params'          => $params,
                'data'            => $data,
                'percent'         => $percent->value,
            ]
        );
    }

    protected function findParamForId(array $ids = []): array
    {
        $params          = Param::whereIn('id', $ids)->get();
        $treatmentParams = [];
        foreach ($params as $item) {
            $treatmentParams[] = $item;
        }
        return $treatmentParams;
    }

    public function step2(Request $request)
    {
        $report = Template::where('company_id', $request->get('id'))->first();
        $data   = Data::where('template_id', $report->id)->where('year', $request->get('year'))->first();

        if ($report->params === null) {
            return redirect('template/' . $report->id . '/edit')->with('error', 'Заполните параметры для шаблона ' . $report->company->company_name);
        }

        $params = Param::all()->whereIn('id', array_keys($report->params))->keyBy('id')->toArray();
        $months = Months::get();
        unset($months[12], $months[13], $months[14], $months[15]);

        $existingData = [];

        if (null !== $data) {
            $existingData = $data->data;
        }

        return view(
            'plan.step2',
            [
                'months'       => $months,
                'report'       => Param::getSortedParams($this->findParamForId($report->params)),
                'year'         => $request->get('year'),
                'existingData' => $existingData,
                'params'       => $params,
                'data'         => $data,
            ]
        );
    }

    public function update(Request $request, $id)
    {
        $data = Data::where('template_id', $id)->where('year', $request->get('year'))->first();

        if (null === $data) {
            return redirect('/plan')->with('error', 'Данных по такому году и шаблону не существует!');
        }

        $newData    = $this->compareData($data->data, $request->get('data'), self::TYPE_DATA);
        $newFact    = $this->compareData($data->fact_previous, $request->get('fact_previous'), self::TYPE_FACT_PREVIOUS);
        $newPredict = $this->compareData($data->predict_current, $request->get('predict_current'), self::TYPE_PREDICT_CURRENT);

        $data->data            = $newData;
        $data->fact_previous   = $newFact;
        $data->predict_current = $newPredict;

        $data->save();

        return redirect('/plan')->with('success', 'Корректировка данных произошла успешно!');
    }

    private function compareData(array $data, array $requestData, string $type): array
    {
        $newData = [];

        foreach (array_keys($data) as $k) {
            $treatedData = $this->treatmentDataItem($data[$k], $requestData[$k], $type);
            $newData[$k] = $treatedData;
        }
        return $newData;
    }

    private function treatmentDataItem(array &$data, array $requestData, string $type): array
    {
        $treatmentDataItem = [];
        $months            = Months::get();
        unset($months[12], $months[13], $months[14], $months[15]);

        if ($type === self::TYPE_DATA) {
            foreach ($months as $key => $value) {
                $newData             = [
                    'plan'               => $this->getPlanValue($data, $requestData, $key),
                    'comment'            => $this->getComment($data, $key),
                    'comment_deviations' => $this->getCommentDeviation($requestData, $key),
                ];
                $treatmentDataItem[] = $newData;
            }
            return $treatmentDataItem;
        }

        if ($type === self::TYPE_FACT_PREVIOUS) {
            $data[self::TYPE_FACT_PREVIOUS] = $this->getFactPreviousValue($data, $requestData);
            return $data;
        }

        if ($type === self::TYPE_PREDICT_CURRENT) {
            $data[self::TYPE_PREDICT_CURRENT] = $this->getPredictCurrentValue($data, $requestData);
            return $data;
        }

        return [];
    }

    private function getPlanValue(array &$data, array $newData, int $monthId): ?float
    {
        return $data[$monthId]['plan'] = $newData[$monthId]['plan'] ?? $data[$monthId]['plan'];
    }

    private function getFactPreviousValue(array &$data, array $newData): ?float
    {
        return $data['fact_previous'] = $newData['fact_previous'] ?? $data['fact_previous'];
    }

    private function getPredictCurrentValue(array &$data, array $newData): ?float
    {
        return $data['predict_current'] = $newData['predict_current'] ?? $data['predict_current'];
    }

    private function getComment(array &$data, int $monthId): ?string
    {
        return $data[$monthId]['comment'];
    }

    private function getCommentDeviation(array &$newData, int $monthId): ?string
    {

src/resources/views/plan/adjustment.blade.php
@extends('adminlte::page')

@section('title', 'Редактировать шаблон отчёта')

@section('content')
    <div class="row">
        <div class="col-12">
            <form method="post" action="{{ route('plan.update', request()->get('id')) }}">
                @csrf
                @method('PATCH')
                <input type="hidden" name="report_id" value="{{ request()->get('id') }}">
                <input type="hidden" name="year" value="{{ request()->get('year') }}">
                <input type="hidden" id='percent' name="percentOfDeviation" value="{{ $percent }}">

                <div class="card">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div><br/>
                    @endif
                    <div class="card-body table-responsive p-0" style="height: 100vh;">
                        <table class="table table-head-fixed">
                            <thead>
                            <tr>
                                <th rowspan="2">Индекс</th>
                                <th rowspan="2">Показатель</th>
                                <th colspan="2" rowspan="2" style='text-align: center;'>Факт предыдущего года</th>
                                <th colspan="2" rowspan="2" style='text-align: center;'>Прогноз до конца текущего года</th>
                                @foreach($months as $month)
                                    <th style="text-align: center;" colspan="1">{{ $month }}</th>
                                @endforeach
                            </tr>
                            <tr>
                                @foreach($months as $month)
                                    <th style="text-align: center; position: sticky; top: 48px; background-color: white;">
                                        план
                                    </th>
                                    <th style="text-align: center; position: sticky; top: 48px; background-color: white;">
                                        корректировка
                                    </th>
                                @endforeach
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($report as $item)
                                <tr>
                                    <td>{{ $item['paragraph'] }}</td>
                                    <td>{{ $item['name'] }}</td>
                                    <td>
                                        <input style='width: 100px;' type="number" class="form-control" name='fact_previous[{{ $item['id'] }}][fact_previous]'
                                               value='{{ (empty($data->fact_previous[$item['id']]['fact_previous']) ? null : $data->fact_previous[$item['id']]['fact_previous']) }}' disabled>
                                    </td>
                                    <td>
                                        <input style='width: 100px;' type="number" class="form-control" name='fact_previous[{{ $item['id'] }}][fact_previous]'>
                                    </td>
                                    <td>
                                        <input style='width: 100px;' type="number" class="form-control" name='predict_current[{{ $item['id'] }}][predict_current]'
                                               value='{{ (empty($data->predict_current[$item['id']]['predict_current']) ? null : $data->predict_current[$item['id']]['predict_current']) }}' disabled>
                                    </td>
                                    <td>
                                        <input style='width: 100px;' type="number" class="form-control" name='predict_current[{{ $item['id'] }}][predict_current]'>
                                    </td>
                                    @foreach($months as $monthId => $month)
                                        <td>
                                            <input class="form-control js-plan"
                                                   style='width: 100px; text-align: center;' type="number"
                                                   data-id='{{ $item['id'] . $monthId }}'
                                                   name="data[{{ $item['id'] }}][{{ $monthId }}][plan]"
                                                   value="{{ (empty($existingData[$item['id']][$monthId]['plan']) ? null : $existingData[$item['id']][$monthId]['plan']) }}"
                                                   disabled>
                                        </td>
                                        <td>
                                            <input class="form-control js-adjust"
                                                   style='width: 100px; text-align: center;' type="number"
                                                   name="data[{{ $item['id'] }}][{{ $monthId }}][plan]"
                                                   data-id='{{ $item['id'] . $monthId }}'>
                                            <textarea class='form-control mt-1' style='display: none; width: 100px;'
                                                      placeholder="Комментарий к плану"
                                                      data-id='{{ $item['id'] . $monthId }}'
                                                      name="data[{{ $item['id'] }}][{{ $monthId }}][comment_deviations]">{{ (empty($existingData[$item['id']][$monthId]['comment_deviations']) ? null : $existingData[$item['id']][$monthId]['comment_deviations']) }}</textarea>
                                        </td>
                                    @endforeach
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Скорректировать данные</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('page-js-script')
    <script type="text/javascript">
        $(document).ready(function () {
            $('.js-adjust').on('change', function () {
                var $adjust = $(this);
                var $plan = $adjust.closest('tr').find('.js-plan[data-id="' + $adjust.data('id') + '"]');
                var $comment = $adjust.closest('tr').find('textarea[data-id="' + $adjust.data('id') + '"]');
                var getPercent = $('#percent').attr('value');

                if (isNaN(parseFloat($adjust.val())) || isNaN(parseFloat($plan.val()))) {
                    return;
                }
                var percent = parseFloat($adjust.val()) * 100 / parseFloat($plan.val()) - 100;

                var maxPercentPositive = getPercent;
                var maxPercentNegative = -getPercent;

                if (percent >= maxPercentPositive && percent !== 0) {
                    return $comment['attr']('required', true) && $comment['show']();
                } else if (percent <= maxPercentNegative && percent !== 0) {
                    return $comment['attr']('required', true) && $comment['show']();
                } else {
                    return $comment['removeAttr']('required', true) && $comment['hide']();
                }
            })
        });
    </script>
@stop

src/resources/views/plan/create.blade.php
@extends('adminlte::page')

@section('title', 'Выбор отчётного года и шаблона')

@section('content')
    <div id='app'>
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Выберите шаблон и отчётный год</h3>
            </div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br/>
                @endif
                    <form method="post" action="{{ route('plan.step2') }}">
                        @csrf
                        <div class="card-body">
                            <div class="col-3">
                                <div class="form-group" id="param_list">
                                    <label for="report_id">Шаблон</label>
                                    <select class="form-control js-params" id="report_id" name="report_id" required>
                                        <option value="" disabled selected hidden>Выберите шаблон...</option>
                                        @foreach ($reports as $report)
                                            <option value='{{ $report->company_id }}'>{{ $report->company->company_name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group" id="param_list">
                                    <label for="year">Год</label>
                                    <select class="form-control js-params" id="year" name="year" required>
                                        <option value="" disabled selected hidden>Выберите год...</option>
                                        @foreach ($years as $year)
                                            <option id="{{ $year }}">{{ $year }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Перейти в таблицу для заполнения данных</button>
                        </div>
                    </form>
            </div>
        </div>
    </div>
@endsection
@section('page-js-script')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#company_id').select2();
            $('#report_id').select2();
            $('.js-params').select2();
        });
    </script>
@stop

src/resources/views/plan/edit.blade.php
@extends('adminlte::page')

@section('title', 'Редактировать шаблон отчёта')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Обновить шаблон отчёта</h1>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br/>
            @endif
            <form method="post" action="{{ route('plan.update', $report->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="company_id">Муниципалитет:</label>
                    <input type="text" class="form-control" id="company_id" name="company_id"
                           value="{{ $report->company_id }}" required/>
                </div>
                <div class="form-group">
                    <label for="name">Показатели:</label>
                    @foreach($report->params as $param)
                        <input type="text" class="form-control" id="params" name="params" value="{{ $param }}"
                               required/>
                    @endforeach
                </div>
                <button type="submit" class="btn btn-primary">Обновить</button>
            </form>
        </div>
    </div>
@endsection

src/resources/views/plan/step2.blade.php
@extends('adminlte::page')

@section('title', 'Добавление даннные в таблицу')

@section('content')
    <div id="app">
        <div class="row">
            <div class="col-12">
                <form method="post" action="{{ route('plan.store') }}">
                    @csrf
                    <input type="hidden" name="report_id" value="{{ request()->get('id') }}">
                    <input type="hidden" name="year" value="{{ request()->get('year') }}">
                    <div class="card">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <div class="card-body table-responsive p-0" style="height: 100vh;">
                            <table class="table table-head-fixed">
                                <thead>
                                    <tr>
                                        <th rowspan="2">Индекс</th>
                                        <th rowspan="2">Показатель</th>
                                        <th colspan="1" rowspan="2" style='text-align: center;'>Факт предыдущего года</th>
                                        <th colspan="1" rowspan="2" style='text-align: center;'>Прогноз до конца текущего года</th>
                                        @foreach($months as $month)
                                            <th style="text-align: center;" colspan="1">{{ $month }}</th>
                                        @endforeach
                                    </tr>
                                    <tr>
                                        @foreach($months as $month)
                                            <th style="text-align: center; position: sticky; top: 48px; background-color: white;" colspan="1">
                                                план
                                            </th>
                                        @endforeach
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($report as $item)
                                    <tr>
                                        <td>{{ $item['paragraph'] }}</td>
                                        <td>{{ $item['name'] }}</td>
                                        <td>
                                            <input style='width: 100px;' type="number" class="form-control" name='fact_previous[{{ $item['id'] }}][fact_previous]'
                                                   value='{{ (empty($data->fact_previous[$item['id']]['fact_previous']) ? null : $data->fact_previous[$item['id']]['fact_previous']) }}'>
                                        </td>
                                        <td>
                                            <input style='width: 100px;' type="number" class="form-control" name='predict_current[{{ $item['id'] }}][predict_current]'
                                                   value='{{ (empty($data->predict_current[$item['id']]['predict_current']) ? null : $data->predict_current[$item['id']]['predict_current']) }}'>
                                        </td>
                                        @foreach($months as $monthId => $month)
                                            <td>
                                                <input class="form-control" style='width: 100px;' type="number" name="data[{{ $item['id'] }}][{{ $monthId }}][plan]"
                                                       value="{{ (empty($existingData[$item['id']][$monthId]['plan']) ? null : $existingData[$item['id']][$monthId]['plan']) }}">
                                                <textarea class='form-control mt-1' style='width: 100px;' placeholder="Комментарий к плану"
                                                          name="data[{{ $item['id'] }}][{{ $monthId }}][comment]">{{ (empty($existingData[$item['id']][$monthId]['comment']) ? null : $existingData[$item['id']][$monthId]['comment']) }}</textarea>
                                            </td>
                                        @endforeach
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Добавить данные</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection